texts = [
    "Hello, World", 
    "Rust", 
    "Lorem Ipsum", 
    "Lorem ipsum dolor sit amet", 
    "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
]
num_wallpapers_per_text = 50
width = 3840
height = 2160

[color_range]
r = [0, 64]  # Red channel range
g = [0, 32]  # Green channel range
b = [0, 32] # Blue channel range

